<link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet" />
<div class="body-inner">
    <div class="box-container logged-in">
        <h2>Bunting scripts <strong>removed successfully</strong></h2>
        <p>The Bunting tracking script has been successfully removed from your store. Bunting is no longer tracking your visitors.</p>
        <br>
        <h3>Uninstalling the app</h3>
        <p>If you installed the extension through the Extension Manager, use that to uninstall it.</p>
        <p>Alternatively, run the appropriate uninstall command "magento module:uninstall ..."</p>
        <p>Finally, to uninstall manually delete the extension directory and delete the database table "bunting_core_bunting".</p>
        <br>
        <p><strong>We're sorry to see you go, but thank you for using Bunting!</strong></p>
        <br>
        <a href="<?php echo $this->getUrl("bunting/index/index"); ?>" class="btn btn-primary btn-lg" >Back to the install page</a>
    </div>
</div>